### Register User
POST http://localhost:5000/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "t3St1234_"
}

### Login User
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "t3St1234_"
}
